### ISSUE TITLE
Error handling for CRITICAL timestamp audio_recorder Raw audio buffer full.

### ISSUE THREAD

**Issue by fmacrae** [google-coral/project-keyword-spotter#12]
```
  def _enqueue_raw_audio(self, in_data, *_):  # unused args to match expected
    try:
      self._raw_audio_queue.put((in_data, time.time()), block=False)
      return None, pyaudio.paContinue
    except queue.Full:
      error_message = "Raw audio buffer full."
      logger.critical(error_message)
      # raise TimeoutError(error_message) #just ignoring if we run out of space - it'll mean dropping frames but if we drop below realtime then happy to let us catch up.
      while not self._raw_audio_queue.empty():
        self._raw_audio_queue.get()
```
Was getting odd behaviour when _enqueue_raw_audio hit the queue.Full error handler.  Although I think the error was passed up to classify_audio in model.py and the error was output there's no code that seems to handle it.  So it seems to stall and not exit the loop.  I just popped in some nasty workarounds by increasing the max_queue_chunks to 12000 and putting the instructions to clear down the queue if it fills.  Assume I'm hitting it due to the rPi not keeping up with realtime if it gets tied up doing something else temporarily.  I'm using it to send bluetooth keyboard commands so that might be my problem.  Thought worth sharing in case others hit this when reusing the code.

**Comment by manoj7410** [comment]
@fmacrae Can you tell me how to reproduce this issue at my end?

**Comment by fmacrae** [comment]
Hi @manoj7410 I was seeing this error while trying to implement a passive voice keyboard - https://github.com/fmacrae/BTSquawk has the full code and instruction on how to set it up.  The error was seen after a fair bit of testing like 5 minutes of it listening and sending bluetooth keyboard outputs.  The workaround above seemed to resolve it.
