### ISSUE TITLE
Problem 5 feedback

### ISSUE THREAD

**Issue by el-tocino** [google-coral/project-keyword-spotter#14]
See also issue #3 

When will the update to do different words happen?   Would like to add some camera-specific type words and potentially remove a few others that aren't needed?

**Comment by ned-kelly** [comment]
Yep, i'd love to also be able to use this to detect custom phrases in a Gym environment - such as "30 seconds to go" or "keep the weights up" so that way we can monitor staff are properly performing their duties.

**Comment by hjonnala** [comment]
Unfortunately, as of now, there are no planned updates for that project or the model.

Thanks
