### ISSUE TITLE
Plans to enable training on own audio / keywords?

### ISSUE THREAD

**Issue by nmstoker** [google-coral/project-keyword-spotter#3]
Thanks for releasing this project.

I did see your [comment here](https://github.com/google-coral/project-keyword-spotter#problem-5-i-need-a-keyphrase-that-is-not-provided-by-the-model) but thinking beyond that, do you expect to release code to let people train on their own audio / keyword data? If so, what is the expected timeframe?

**Comment by rouyunpan** [comment]
I am also looking forward to it. Your results are great
I use this project to integrate my robot. It works well.
https://www.youtube.com/watch?v=EuHL3EZSrDY

**Comment by mtyka** [comment]
Yes, we're working on that but I can't promise you an exact release date.

**Comment by nmstoker** [comment]
@mtyka - now that we're five and a half months on, is there any more clarity on a timeframe for this?
