### ISSUE TITLE
audio_recorder.TimeoutError: Audio capture timed out after 0.0 seconds. (Solved??)

### ISSUE THREAD

**Issue by charliejgallo** [google-coral/project-keyword-spotter#4]
Problem: Audio Capture timed out after a second every time 

`python3 run_model.py --mic 3 --sample_rate_hz 48000`

testing with a rasperrypi4, coral usb accelerator and a logitech usb mic (48000hz),
the error stopped after changing  timeout_factor (line 78 in  audio_recorder.py) from 4 to 12, 
no issues after that (tested with run_model.py and run_hearing_snake.py)

here is attached the terminal log of the error...

[error log project key spotter.txt](https://github.com/google-coral/project-keyword-spotter/files/3736614/error.log.project.key.spotter.txt)

(new to github and only a hobbyist, sorry if something is not described the proper way)

**Comment by mtyka** [comment]
Yes, changing the timeout_factor is what I was going to recommend. Seems like you solved it ! :)
