### ISSUE TITLE
Code samples for conversion

### ISSUE THREAD

**Issue by mpariente** [google-coral/project-keyword-spotter#8]
Hi, thanks for the resources, that's really cool ! 

Could you provide some code snippet showing how the model was converted to a quantized model? If I follow the tflite and coral docs, I always get some float32 input node and some quantize ops that cannot be mapped to EdgeTPU.

Did you use quantization aware training or post-training quantization (with representative dataset or not)? 
Thanks in advance

**Comment by mtyka** [comment]
We haven't released yet any way to retrain this model, but we're working on it. Hopefully soon !
